"""Create a private .env from validated local Ollama and Tesseract settings."""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import urllib.request
from collections import OrderedDict
from collections.abc import Iterator
from contextlib import contextmanager
from datetime import datetime, timezone
from pathlib import Path

from resume_analyzer.config import PipelineConfig
from resume_analyzer.environment import read_env_file
from resume_analyzer.web.config import WebSettings

SELECTED_MODEL = "gemma3:4b"
REQUIRED_LANGUAGES = ("eng", "ara", "eng+ara")


def _ollama_models(base_url: str) -> set[str]:
    request = urllib.request.Request(f"{base_url.rstrip('/')}/api/tags")
    with urllib.request.urlopen(request, timeout=5) as response:
        payload = json.load(response)
    return {str(item.get("name", "")) for item in payload.get("models", [])}


def _tesseract_language_works(executable: Path, tessdata: Path, language: str) -> bool:
    environment = os.environ.copy()
    environment["TESSDATA_PREFIX"] = str(tessdata.resolve())
    completed = subprocess.run(
        [str(executable), "--print-parameters", "-l", language],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=15,
        check=False,
        env=environment,
    )
    return completed.returncode == 0


@contextmanager
def _temporary_environment(values: dict[str, str]) -> Iterator[None]:
    previous = {key: os.environ.get(key) for key in values}
    os.environ.update(values)
    try:
        yield
    finally:
        for key, value in previous.items():
            if value is None:
                os.environ.pop(key, None)
            else:
                os.environ[key] = value


def _write_env(path: Path, values: OrderedDict[str, str]) -> None:
    lines = [
        "# Private machine-local configuration generated by scripts/configure_env.py.",
        "# Do not commit this file.",
        "",
    ]
    lines.extend(f"{key}={value}" for key, value in values.items())
    temporary = path.with_suffix(path.suffix + ".new")
    temporary.write_text("\n".join(lines) + "\n", encoding="utf-8")
    os.replace(temporary, path)


def configure(root: Path, model: str) -> Path:
    example_path = root / ".env.example"
    env_path = root / ".env"
    values = read_env_file(example_path)
    if not values:
        raise RuntimeError(f"No configuration fields found in {example_path}")
    existing = read_env_file(env_path)
    values.update(existing)

    base_url = values.get("RESUME_OLLAMA_BASE_URL", "http://127.0.0.1:11434")
    if model not in _ollama_models(base_url):
        raise RuntimeError(f"Validated model is not installed in Ollama: {model}")

    detected_tesseract = shutil.which("tesseract") or str(
        Path(r"C:\Program Files\Tesseract-OCR\tesseract.exe")
    )
    executable = Path(detected_tesseract)
    tessdata = root / "runtime" / "tessdata"
    if not executable.is_file():
        raise RuntimeError(f"Tesseract executable was not found: {executable}")
    failed_languages = [
        language
        for language in REQUIRED_LANGUAGES
        if not _tesseract_language_works(executable, tessdata, language)
    ]
    if failed_languages:
        raise RuntimeError("Tesseract language validation failed: " + ", ".join(failed_languages))

    values.update(
        {
            "RESUME_TEMP_DIR": "runtime/temp",
            "RESUME_OUTPUT_DIR": "runtime/outputs",
            "RESUME_ENABLE_REWRITES": "true",
            "RESUME_AI_PROVIDER": "ollama",
            "RESUME_AI_MODEL": model,
            "RESUME_AI_TIMEOUT_SECONDS": "90",
            "RESUME_AI_MAX_RETRIES": "1",
            "RESUME_AI_TEMPERATURE": "0",
            "RESUME_AI_SEED": "42",
            "RESUME_AI_MAX_TOKENS": "900",
            "RESUME_OLLAMA_KEEP_ALIVE": "5m",
            "RESUME_TRANSFORMERS_CACHE_DIR": "runtime/model_cache",
            "TESSERACT_CMD": str(executable.resolve()),
            "TESSERACT_LANGUAGES": "eng+ara",
            "TESSDATA_PREFIX": "runtime/tessdata",
        }
    )

    with _temporary_environment(dict(values)):
        pipeline = PipelineConfig.from_env()
        web = WebSettings.from_env()
    if pipeline.ai_provider != "ollama" or pipeline.ai_model != model:
        raise RuntimeError("Application settings did not accept the selected Ollama model")
    if pipeline.ocr_language != "eng+ara" or not web.output_dir:
        raise RuntimeError("Application settings did not accept the OCR/runtime paths")
    web.prepare_runtime_directories()

    if env_path.exists():
        timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
        backup = root / "runtime" / "config_backups" / f"env-{timestamp}.backup"
        backup.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(env_path, backup)
        print(f"backed up existing configuration to {backup.relative_to(root)}")
    _write_env(env_path, values)
    print(
        json.dumps(
            {
                "env_file": ".env",
                "ollama": {"base_url": base_url, "model": model, "validated": True},
                "ocr": {
                    "languages": list(REQUIRED_LANGUAGES),
                    "tesseract_configured": True,
                    "local_tessdata": True,
                },
                "rewrites_enabled": True,
                "secrets_printed": False,
            },
            indent=2,
        )
    )
    return env_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default=SELECTED_MODEL)
    arguments = parser.parse_args()
    root = Path(__file__).resolve().parents[1]
    try:
        configure(root, arguments.model)
    except (OSError, RuntimeError, subprocess.SubprocessError) as exc:
        print(f"Configuration failed: {exc}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
